// SurveyField contains logic to render a single label and text input

import React from 'react';

// destructuring the error, and touched objects out of meta object
function SurveyField( {input, label, meta: {error, touched} } ) {

// {input} is the same as props.input
// props.input has all the event handlers generated by redux forms... can console.log(props) to see what's in there
  // console.log(input)
  return (
    <div>
      <label> { label } </label>
      <input {...input} style={{ marginBotton: '5px' }} />
      <div className='red-text' style={{ marginBottom: '20px' }}>
        { touched && error }
      </div>
    </div>
  );
}

export default SurveyField;
